spring:
  datasource:
    platform: cassandra
    url: jdbc:cassandra://localhost:9042
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
#      schema-action: RECREATE
      keyspace-name: searches
      port: 9042
    elasticsearch:
      clusterName: docker-cluster
      clusterNodes: localhost:9300
  main.web-application-type: servlet

logging.level.org.springframework.cassandra: DEBUG
server:
  port: 8081
